// scripts/seed-data/companies.js
// ============================================================
// ۳۰ شرکت — همان‌هایی که قبلاً تعریف کردیم
// با فیلد imageKeywords برای تولید خودکار تصویر
// ============================================================

const companies = [
  // ============================================================
  // بخش ۱: خرما و خشکبار (۱۰ شرکت)
  // ============================================================
  {
    name: "Mahmoud Ibrahim Abdel-Rahman",
    companyName: "Al Barakah Dates Trading",
    email: "mahmoud@albarakah-dates.com",
    companyEmail: "export@albarakah-dates.com",
    plan: "GOLD",
    country: "Egypt", city: "Cairo", countryCode: "EG", postalCode: "11511",
    businessType: "Manufacturer/ OEM", employeeCount: "51-200",
    phone: "+20-100-2345671", website: "https://www.albarakah-dates.com",
    address: "Plot 12, Industrial Zone, 6th of October City, Giza Governorate",
    bio: "<p>Al Barakah Dates Trading is one of Egypt's leading producers and exporters of premium dates and dried fruits. Founded in 2003, we operate 800 hectares of date palm groves across Siwa Oasis, El-Kharga, and the Nile Delta, specializing in Medjool, Siwa, Hayani, and Barhi varieties.</p><p>Our modern processing facility near Cairo produces over 12,000 metric tons annually, with a fully automated sorting, cleaning, and packaging line. We are <strong>ISO 22000, HACCP, BRC, and GlobalG.A.P.</strong> certified, and ship to more than 35 countries across Europe, Asia, and North America.</p>",
    socialLinks: {
      contactPerson: "Mahmoud Ibrahim Abdel-Rahman", contactDesignation: "Export Director",
      establishedYear: "2003", memberSince: "2019", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "Europe, GCC, North America, Southeast Asia, Australia",
      domesticMarkets: "Egypt, Libya, Sudan",
      certifications: "ISO 22000, HACCP, BRC, GlobalG.A.P., EU Organic, USDA Organic",
      languages: ["Arabic", "English", "French"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "dried-fruits",
    logoKeyword: "dates,farm", coverKeyword: "date,palm,grove", galleryKeywords: ["dates,market", "dates,packaging", "date,palm", "dates,dried", "medjool,dates", "dates,factory"],
  },
  {
    name: "Fatma Abdallah Salem",
    companyName: "Siwa Oasis Organic Date Farm",
    email: "fatma@siwa-organics.com", companyEmail: "sales@siwa-organics.com",
    plan: "SILVER", country: "Egypt", city: "Siwa", countryCode: "EG", postalCode: "51714",
    businessType: "Farm / Producer", employeeCount: "11-50",
    phone: "+20-128-8765432", website: "https://www.siwa-organics.com",
    address: "Dakrour Mountain Road, Siwa Oasis, Matrouh Governorate",
    bio: "<p>Siwa Oasis Organic Date Farm is a family-run producer located in the heart of Egypt's Western Desert. Our 120 hectares of organically managed palm groves yield a distinctive range of dates with exceptional sugar content, grown without synthetic fertilizers for over four generations.</p>",
    socialLinks: {
      contactPerson: "Fatma Abdallah Salem", contactDesignation: "Founder & Managing Director",
      establishedYear: "1997", memberSince: "2021", membershipStatus: "SILVER Member",
      marketsCovered: "Europe, GCC", domesticMarkets: "Egypt",
      certifications: "EU Organic, USDA Organic", languages: ["Arabic", "English"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "dried-fruits",
    logoKeyword: "organic,date", coverKeyword: "siwa,oasis", galleryKeywords: ["organic,dates", "date,palm,organic", "desert,farm", "dates,harvest", "siwa,date", "palm,oasis"],
  },
  {
    name: "Khalid Al-Otaibi",
    companyName: "Al Madinah Ajwa Date Factory",
    email: "khalid@ajwa-madinah.sa", companyEmail: "export@ajwa-madinah.sa",
    plan: "GOLD", country: "Saudi Arabia", city: "Medina", countryCode: "SA", postalCode: "42311",
    businessType: "Manufacturer/ OEM", employeeCount: "51-200",
    phone: "+966-55-9876543", website: "https://www.ajwa-madinah.sa",
    address: "Al-Awali District, Industrial Area, Medina",
    bio: "<p>Al Madinah Ajwa Date Factory is a specialized Saudi producer dedicated to the legendary <strong>Ajwa Al-Madinah</strong> dates — a variety exclusively grown in the Medina region and revered across the Islamic world.</p>",
    socialLinks: {
      contactPerson: "Khalid Al-Otaibi", contactDesignation: "General Manager",
      establishedYear: "2008", memberSince: "2018", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "GCC, Southeast Asia, Europe, North Africa", domesticMarkets: "Saudi Arabia",
      certifications: "SFDA, ISO 22000, HACCP, Halal", languages: ["Arabic", "English"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "dried-fruits",
    logoKeyword: "ajwa,date", coverKeyword: "medina,dates", galleryKeywords: ["ajwa,dates", "saudi,dates", "medina,market", "dates,gift", "ajwa,palm", "dates,factory"],
  },
  {
    name: "Faisal bin Abdullah Al-Qahtani",
    companyName: "Qassim Premium Dates Co.",
    email: "faisal@qassim-dates.com", companyEmail: "info@qassim-dates.com",
    plan: "SILVER", country: "Saudi Arabia", city: "Buraydah", countryCode: "SA", postalCode: "51411",
    businessType: "Distributor", employeeCount: "51-200",
    phone: "+966-56-1234567", website: "https://www.qassim-dates.com",
    address: "King Abdulaziz Road, Buraydah, Al-Qassim Province",
    bio: "<p>Qassim Premium Dates Co. is a leading Saudi distributor operating out of Buraydah — the heart of the Kingdom's date-producing region, home to over 8 million palm trees.</p>",
    socialLinks: {
      contactPerson: "Faisal bin Abdullah Al-Qahtani", contactDesignation: "Chief Executive Officer",
      establishedYear: "2012", memberSince: "2020", membershipStatus: "SILVER Member",
      marketsCovered: "GCC, South Asia, North Africa", domesticMarkets: "Saudi Arabia",
      certifications: "SFDA, Halal, ISO 9001", languages: ["Arabic", "English"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "dried-fruits",
    logoKeyword: "qassim,dates", coverKeyword: "saudi,dates,grove", galleryKeywords: ["dates,sukkari", "dates,packaging", "dates,bags", "saudi,market", "date,palm", "dates,shop"],
  },
  {
    name: "Sultan Al-Mansoori",
    companyName: "Al Ain Date Palm Est.",
    email: "sultan@alain-datepalm.ae", companyEmail: "export@alain-datepalm.ae",
    plan: "GOLD", country: "United Arab Emirates", city: "Al Ain", countryCode: "AE", postalCode: "15258",
    businessType: "Farm / Producer", employeeCount: "51-200",
    phone: "+971-50-9876543", website: "https://www.alain-datepalm.ae",
    address: "Al Foah Area, Al Ain, Abu Dhabi Emirate",
    bio: "<p>Al Ain Date Palm Est. is an Emirati family enterprise managing 3,200 date palms in the historic Al Foah oasis — a UNESCO-recognized agricultural heritage site in the emirate of Abu Dhabi.</p>",
    socialLinks: {
      contactPerson: "Sultan Al-Mansoori", contactDesignation: "Managing Partner",
      establishedYear: "1995", memberSince: "2017", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "Europe, East Asia, Australia, GCC", domesticMarkets: "UAE",
      certifications: "ISO 22000, HACCP, Halal, ESMA", languages: ["Arabic", "English"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "dried-fruits",
    logoKeyword: "uae,dates", coverKeyword: "al,ain,oasis", galleryKeywords: ["khalas,dates", "dates,oasis", "date,palm,uae", "dates,factory", "dates,luxury", "dates,almond"],
  },
  {
    name: "Rashed Al-Falasi",
    companyName: "Dubai Premium Nuts & Dates LLC",
    email: "rashed@dubaipremiumnuts.ae", companyEmail: "sales@dubaipremiumnuts.ae",
    plan: "SILVER", country: "United Arab Emirates", city: "Dubai", countryCode: "AE", postalCode: "00000",
    businessType: "Trading Company", employeeCount: "11-50",
    phone: "+971-52-1112233", website: "https://www.dubaipremiumnuts.ae",
    address: "Al Quoz Industrial Area 3, Sheikh Zayed Road, Dubai",
    bio: "<p>Dubai Premium Nuts & Dates LLC is a specialized trader of premium nuts, dates, and dried fruits serving the GCC hospitality and retail sectors. Our 4,000 sqm facility in Al Quoz combines roasting, salting, blending, and repackaging.</p>",
    socialLinks: {
      contactPerson: "Rashed Al-Falasi", contactDesignation: "Head of Trading",
      establishedYear: "2010", memberSince: "2019", membershipStatus: "SILVER Member",
      marketsCovered: "GCC, East Africa, South Asia", domesticMarkets: "UAE, Oman",
      certifications: "HACCP, ISO 22000, Dubai Municipality Food Safety", languages: ["Arabic", "English", "Hindi"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "tree-nuts",
    logoKeyword: "nuts,mixed", coverKeyword: "dubai,market", galleryKeywords: ["mixed,nuts", "pistachios", "almonds", "cashews", "walnuts", "nuts,shop"],
  },
  {
    name: "Sami Ben Youssef",
    companyName: "Deglet Nour Tunisian Dates Export",
    email: "sami@degletnour-tunisia.tn", companyEmail: "export@degletnour-tunisia.tn",
    plan: "GOLD", country: "Tunisia", city: "Tozeur", countryCode: "TN", postalCode: "2210",
    businessType: "Manufacturer/ OEM", employeeCount: "51-200",
    phone: "+216-98-765432", website: "https://www.degletnour-tunisia.tn",
    address: "Zone Industrielle, Route de Nefta, Tozeur",
    bio: "<p>Deglet Nour Tunisian Dates Export is one of Tunisia's premier date exporters, specializing exclusively in the world-renowned <strong>Deglet Nour</strong> variety — often called the 'date of light'.</p>",
    socialLinks: {
      contactPerson: "Sami Ben Youssef", contactDesignation: "Export Manager",
      establishedYear: "2005", memberSince: "2018", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "Europe, North America, East Asia, GCC", domesticMarkets: "Tunisia, Libya, Algeria",
      certifications: "ISO 22000, IFS, EU Organic, HACCP",
      languages: ["Arabic", "French", "English", "Italian"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "dried-fruits",
    logoKeyword: "deglet,date", coverKeyword: "tozeur,palm", galleryKeywords: ["deglet,nour", "tunisian,dates", "date,branch", "dates,export", "tozeur,oasis", "palm,tunisia"],
  },
  {
    name: "Leila Trabelsi",
    companyName: "Sfax Dried Fruits Cooperative",
    email: "leila@sfax-driedfruits.tn", companyEmail: "contact@sfax-driedfruits.tn",
    plan: "BRONZE", country: "Tunisia", city: "Sfax", countryCode: "TN", postalCode: "3000",
    businessType: "Cooperative", employeeCount: "51-200",
    phone: "+216-74-123456", website: null,
    address: "Route de Gabès km 8, Sfax",
    bio: "<p>Sfax Dried Fruits Cooperative represents 85 small-scale producers from the Sfax region of Tunisia. We specialize in sun-dried fruits: figs, apricots, prunes, raisins, and dates.</p>",
    socialLinks: {
      contactPerson: "Leila Trabelsi", contactDesignation: "Cooperative Coordinator",
      establishedYear: "2011", memberSince: "2022", membershipStatus: "FREE Member",
      marketsCovered: "Europe, North Africa", domesticMarkets: "Tunisia",
      certifications: "EU Organic (partial), Fairtrade", languages: ["Arabic", "French"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "dried-fruits",
    logoKeyword: "dried,fruits", coverKeyword: "sun,dried,fruits", galleryKeywords: ["dried,figs", "dried,apricots", "sun,dried", "dried,fruits", "raisins", "figs,dried"],
  },
  {
    name: "Yacine Boumediene",
    companyName: "Biskra Dates Export SPA",
    email: "yacine@biskra-dates.dz", companyEmail: "export@biskra-dates.dz",
    plan: "GOLD", country: "Algeria", city: "Biskra", countryCode: "DZ", postalCode: "07000",
    businessType: "Manufacturer/ OEM", employeeCount: "201-500",
    phone: "+213-661-987654", website: "https://www.biskra-dates.dz",
    address: "Zone Industrielle Nord, Biskra, Wilaya de Biskra",
    bio: "<p>Biskra Dates Export SPA is Algeria's flagship date exporter, operating from the historic Ziban region. Our facility handles 15,000 metric tons per season, ranking us among the top three Algerian exporters of <strong>Deglet Nour</strong>.</p>",
    socialLinks: {
      contactPerson: "Yacine Boumediene", contactDesignation: "Commercial Director",
      establishedYear: "1998", memberSince: "2017", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "Europe, Russia, Southeast Asia, GCC", domesticMarkets: "Algeria, Tunisia, Morocco",
      certifications: "ISO 22000, HACCP, EU Organic, IFS",
      languages: ["Arabic", "French", "English"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "dried-fruits",
    logoKeyword: "algeria,dates", coverKeyword: "biskra,palm", galleryKeywords: ["deglet,nour,algeria", "dates,factory", "date,palm,algeria", "dates,export", "biskra,oasis", "dates,packaging"],
  },
  {
    name: "Amine Bouteflika",
    companyName: "Tolga Sahara Dates Co.",
    email: "amine@tolga-sahara.dz", companyEmail: "sales@tolga-sahara.dz",
    plan: "SILVER", country: "Algeria", city: "Tolga", countryCode: "DZ", postalCode: "07400",
    businessType: "Farm / Producer", employeeCount: "11-50",
    phone: "+213-770-111222", website: "https://www.tolga-sahara.dz",
    address: "Route de Sidi Okba, Tolga, Wilaya de Biskra",
    bio: "<p>Tolga Sahara Dates Co. is a family-owned Algerian date farm and exporter located in the Tolga palm groves — considered the most prestigious terroir in Algeria for <strong>Deglet Nour</strong>.</p>",
    socialLinks: {
      contactPerson: "Amine Bouteflika", contactDesignation: "Owner & Manager",
      establishedYear: "1987", memberSince: "2023", membershipStatus: "SILVER Member",
      marketsCovered: "Europe, GCC, Turkey", domesticMarkets: "Algeria",
      certifications: "HACCP, ONSSA", languages: ["Arabic", "French"],
    },
    primaryCategory: "nuts-seeds-dried-fruits", primarySubCategory: "dried-fruits",
    logoKeyword: "tolga,dates", coverKeyword: "sahara,palm", galleryKeywords: ["tolga,dates", "dates,algeria", "date,palm,desert", "dates,branches", "dates,harvest", "sahara,oasis"],
  },

  // ============================================================
  // بخش ۲: روغن زیتون (۱۰ شرکت)
  // ============================================================
  {
    name: "Mohamed Ali Ben Salah",
    companyName: "Tunisian Olive Oil Company",
    email: "mohamed@tunisian-oliveoil.tn", companyEmail: "export@tunisian-oliveoil.tn",
    plan: "GOLD", country: "Tunisia", city: "Sfax", countryCode: "TN", postalCode: "3000",
    businessType: "Manufacturer/ OEM", employeeCount: "201-500",
    phone: "+216-98-112233", website: "https://www.tunisian-oliveoil.tn",
    address: "Zone Industrielle Poudrière II, Sfax",
    bio: "<p>Tunisian Olive Oil Company is one of the country's largest olive oil producers, ranking among the <strong>top 5 global exporters</strong> of Tunisian olive oil. We span 6,800 hectares across Sfax, Sidi Bouzid, and Mahdia.</p>",
    socialLinks: {
      contactPerson: "Mohamed Ali Ben Salah", contactDesignation: "Export Director",
      establishedYear: "1999", memberSince: "2016", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, USA, Canada, East Asia, Australia, GCC", domesticMarkets: "Tunisia",
      certifications: "ISO 22000, IFS, BRC, EU Organic, USDA Organic, Kosher",
      languages: ["Arabic", "French", "English"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "olive,oil", coverKeyword: "olive,grove", galleryKeywords: ["olive,oil,bottle", "olive,tree", "olive,harvest", "olive,mill", "evoo", "olive,oil,glass"],
  },
  {
    name: "Rim Ben Amor",
    companyName: "Sousse Olive Groves",
    email: "rim@sousse-olivegroves.tn", companyEmail: "sales@sousse-olivegroves.tn",
    plan: "SILVER", country: "Tunisia", city: "Sousse", countryCode: "TN", postalCode: "4000",
    businessType: "Manufacturer/ OEM", employeeCount: "11-50",
    phone: "+216-73-987654", website: "https://www.sousse-olivegroves.tn",
    address: "Route de Kairouan km 5, Sousse",
    bio: "<p>Sousse Olive Groves is a mid-sized Tunisian producer focused on <strong>single-origin extra virgin olive oil</strong> from the Sahel region.</p>",
    socialLinks: {
      contactPerson: "Rim Ben Amor", contactDesignation: "Sales & Marketing Manager",
      establishedYear: "2009", memberSince: "2019", membershipStatus: "SILVER Member",
      marketsCovered: "EU, USA, Japan", domesticMarkets: "Tunisia",
      certifications: "EU Organic, ISO 22000, HACCP", languages: ["Arabic", "French", "English"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "evoo,tunisia", coverKeyword: "olive,tunisia", galleryKeywords: ["evoo,bottle", "olive,oil", "olives", "olive,tree", "olive,oil,jar", "olive,milling"],
  },
  {
    name: "Nizar Ben Romdhane",
    companyName: "Cap Bon Organic Olive Oil",
    email: "nizar@capbon-oliveoil.tn", companyEmail: "info@capbon-oliveoil.tn",
    plan: "GOLD", country: "Tunisia", city: "Nabeul", countryCode: "TN", postalCode: "8000",
    businessType: "Farm / Producer", employeeCount: "51-200",
    phone: "+216-72-334455", website: "https://www.capbon-oliveoil.tn",
    address: "Route de Tunis km 3, Nabeul, Cap Bon Peninsula",
    bio: "<p>Cap Bon Organic Olive Oil is a fully certified organic producer operating 1,400 hectares on the Cap Bon peninsula — Tunisia's most humid microclimate, ideal for high-polyphenol EVOO.</p>",
    socialLinks: {
      contactPerson: "Nizar Ben Romdhane", contactDesignation: "Founder",
      establishedYear: "2006", memberSince: "2017", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, East Asia, North America", domesticMarkets: "Tunisia",
      certifications: "EU Organic, USDA Organic, JAS Organic, ISO 22000, Kosher",
      languages: ["Arabic", "French", "English"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "organic,evoo", coverKeyword: "cap,bon,olive", galleryKeywords: ["organic,olive,oil", "evoo,green", "olive,leaf", "cold,press", "olive,oil,glass", "olive,farm"],
  },
  {
    name: "Youssef El Amrani",
    companyName: "Atlas Mountain Olive Oil",
    email: "youssef@atlas-oliveoil.ma", companyEmail: "export@atlas-oliveoil.ma",
    plan: "GOLD", country: "Morocco", city: "Marrakech", countryCode: "MA", postalCode: "40000",
    businessType: "Manufacturer/ OEM", employeeCount: "51-200",
    phone: "+212-661-998877", website: "https://www.atlas-oliveoil.ma",
    address: "Route de Fès km 12, Marrakech",
    bio: "<p>Atlas Mountain Olive Oil is a Moroccan producer specializing in premium EVOO from the <strong>Picholine Marocaine</strong> variety, grown on the slopes of the High Atlas mountains above 800 m.</p>",
    socialLinks: {
      contactPerson: "Youssef El Amrani", contactDesignation: "Managing Director",
      establishedYear: "2008", memberSince: "2018", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, North America, Japan", domesticMarkets: "Morocco",
      certifications: "EU Organic, USDA Organic, ISO 22000, IFS",
      languages: ["Arabic", "French", "English"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "atlas,olive", coverKeyword: "atlas,mountains", galleryKeywords: ["picholine,olive", "morocco,olive,oil", "atlas,olive,tree", "olive,oil,bottle", "olive,grove", "olive,oil,press"],
  },
  {
    name: "Khadija Bennani",
    companyName: "Fès Olive & Argan Cooperative",
    email: "khadija@fes-olive.ma", companyEmail: "sales@fes-olive.ma",
    plan: "SILVER", country: "Morocco", city: "Fès", countryCode: "MA", postalCode: "30000",
    businessType: "Cooperative", employeeCount: "51-200",
    phone: "+212-662-334455", website: "https://www.fes-olive.ma",
    address: "Route d'Immouzer, Fès",
    bio: "<p>Fès Olive & Argan Cooperative is a women-led cooperative producing both <strong>extra virgin olive oil and cosmetic-grade argan oil</strong>.</p>",
    socialLinks: {
      contactPerson: "Khadija Bennani", contactDesignation: "President",
      establishedYear: "2004", memberSince: "2020", membershipStatus: "SILVER Member",
      marketsCovered: "EU, USA, Japan, South Korea", domesticMarkets: "Morocco",
      certifications: "EU Organic, USDA Organic, Fairtrade, IGP Argane",
      languages: ["Arabic", "French", "English", "Amazigh"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "argan,oil", coverKeyword: "morocco,olive", galleryKeywords: ["argan,oil", "argan,nuts", "olive,oil", "women,cooperative", "morocco,farm", "argan,tree"],
  },
  {
    name: "Mostafa Kamel",
    companyName: "Sinai Olive Oil Producers",
    email: "mostafa@sinai-oliveoil.com", companyEmail: "export@sinai-oliveoil.com",
    plan: "BRONZE", country: "Egypt", city: "El-Arish", countryCode: "EG", postalCode: "45511",
    businessType: "Cooperative", employeeCount: "11-50",
    phone: "+20-100-6677889", website: null,
    address: "El-Rawda Village, Central Sinai, North Sinai Governorate",
    bio: "<p>Sinai Olive Oil Producers is an emerging Egyptian cooperative representing 120 smallholder farmers across the central Sinai plateau.</p>",
    socialLinks: {
      contactPerson: "Mostafa Kamel", contactDesignation: "Director",
      establishedYear: "2016", memberSince: "2023", membershipStatus: "FREE Member",
      marketsCovered: "GCC", domesticMarkets: "Egypt",
      certifications: "HACCP, Egyptian Food Safety", languages: ["Arabic", "English"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "olive,oil", coverKeyword: "sinai,olive", galleryKeywords: ["olive,oil", "sinai,farm", "olive,grove", "olive,harvest", "olive,tree", "olive,oil,bottle"],
  },
  {
    name: "Nabil Shaker Hanna",
    companyName: "Alexandria Olive Press",
    email: "nabil@alexandria-olivepress.com", companyEmail: "info@alexandria-olivepress.com",
    plan: "SILVER", country: "Egypt", city: "Alexandria", countryCode: "EG", postalCode: "21500",
    businessType: "Manufacturer/ OEM", employeeCount: "51-200",
    phone: "+20-128-1112223", website: "https://www.alexandria-olivepress.com",
    address: "Industrial Area, Amreya, Alexandria",
    bio: "<p>Alexandria Olive Press is a modern Egyptian olive oil processor and bottler. We source from over 1,800 hectares across the Western Desert oases (Siwa, Bahariya, Farafra).</p>",
    socialLinks: {
      contactPerson: "Nabil Shaker Hanna", contactDesignation: "Commercial Manager",
      establishedYear: "2007", memberSince: "2018", membershipStatus: "SILVER Member",
      marketsCovered: "EU, USA, GCC", domesticMarkets: "Egypt",
      certifications: "ISO 22000, HACCP, EU Organic (partial)", languages: ["Arabic", "English", "French"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "olive,press", coverKeyword: "alexandria,olive", galleryKeywords: ["olive,press", "olive,oil,factory", "olive,oil,bottle", "olive,milling", "olive,farm", "olive,oil,tank"],
  },
  {
    name: "Bashar Al-Nasser",
    companyName: "Damascus Olive Grove Co.",
    email: "bashar@damascus-olivegroves.sy", companyEmail: "export@damascus-olivegroves.sy",
    plan: "SILVER", country: "Syria", city: "Damascus", countryCode: "SY", postalCode: "00000",
    businessType: "Manufacturer/ OEM", employeeCount: "51-200",
    phone: "+963-11-9876543", website: null,
    address: "Rural Damascus, Al-Kiswah Industrial Zone",
    bio: "<p>Damascus Olive Grove Co. is a Syrian olive oil producer and exporter with a heritage stretching back over 40 years. Our production centers in Rural Damascus and the coastal mountains.</p>",
    socialLinks: {
      contactPerson: "Bashar Al-Nasser", contactDesignation: "Export Manager",
      establishedYear: "1982", memberSince: "2019", membershipStatus: "SILVER Member",
      marketsCovered: "GCC, Turkey, Lebanon", domesticMarkets: "Syria",
      certifications: "HACCP, Syrian Ministry of Agriculture", languages: ["Arabic", "English"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "syria,olive", coverKeyword: "damascus,olive", galleryKeywords: ["syrian,olive,oil", "damascus,olive", "olive,oil,jar", "olive,harvest", "olive,tree", "olive,mill"],
  },
  {
    name: "Rami Al-Halabi",
    companyName: "Aleppo Premium Olive Oil",
    email: "rami@aleppo-oliveoil.sy", companyEmail: "sales@aleppo-oliveoil.sy",
    plan: "BRONZE", country: "Syria", city: "Aleppo", countryCode: "SY", postalCode: "00000",
    businessType: "Trading Company", employeeCount: "11-50",
    phone: "+963-21-1122334", website: null,
    address: "Sheikh Najjar Industrial City, Aleppo",
    bio: "<p>Aleppo Premium Olive Oil is a Syrian trading house specialized in aggregating premium olive oil from smallholder farms across the Idlib and Aleppo countryside.</p>",
    socialLinks: {
      contactPerson: "Rami Al-Halabi", contactDesignation: "Export Coordinator",
      establishedYear: "2014", memberSince: "2022", membershipStatus: "FREE Member",
      marketsCovered: "Turkey, Iraq, GCC", domesticMarkets: "Syria",
      certifications: "HACCP", languages: ["Arabic", "English", "Turkish"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "aleppo,olive", coverKeyword: "aleppo,city", galleryKeywords: ["aleppo,olive,oil", "syrian,olive", "olive,oil,bottle", "olive,press", "olive,grove", "olive,oil,factory"],
  },
  {
    name: "Hedi Ben Slimane",
    companyName: "Mahdia Organic Olive Oil",
    email: "hedi@mahdia-organic.tn", companyEmail: "export@mahdia-organic.tn",
    plan: "GOLD", country: "Tunisia", city: "Mahdia", countryCode: "TN", postalCode: "5100",
    businessType: "Farm / Producer", employeeCount: "51-200",
    phone: "+216-73-556677", website: "https://www.mahdia-organic.tn",
    address: "Route de Sfax km 10, Mahdia",
    bio: "<p>Mahdia Organic Olive Oil is a Tunisian certified organic producer operating 2,100 hectares of <strong>Chemlali and Chetoui</strong> olive groves on the central-eastern coast. Fully organic since 2015.</p>",
    socialLinks: {
      contactPerson: "Hedi Ben Slimane", contactDesignation: "Managing Director",
      establishedYear: "2010", memberSince: "2018", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, Scandinavia, Japan", domesticMarkets: "Tunisia",
      certifications: "EU Organic, USDA Organic, ISO 22000, Kosher", languages: ["Arabic", "French", "English"],
    },
    primaryCategory: "oils-fats-shortenings", primarySubCategory: "specialty-oils",
    logoKeyword: "mahdia,olive", coverKeyword: "tunisia,olive,coast", galleryKeywords: ["organic,evoo", "olive,oil,green", "tunisia,olive", "olive,farm,coast", "olive,harvest", "olive,oil,bottle"],
  },

  // ============================================================
  // بخش ۳: میوه و سبزی (۱۰ شرکت)
  // ============================================================
  {
    name: "Sherif Hosny",
    companyName: "Nile Delta Citrus Export",
    email: "sherif@niledelta-citrus.com", companyEmail: "export@niledelta-citrus.com",
    plan: "GOLD", country: "Egypt", city: "Tanta", countryCode: "EG", postalCode: "31511",
    businessType: "Manufacturer/ OEM", employeeCount: "201-500",
    phone: "+20-100-4455667", website: "https://www.niledelta-citrus.com",
    address: "Agricultural Industrial Zone, Tanta, Gharbia Governorate",
    bio: "<p>Nile Delta Citrus Export is one of Egypt's top citrus exporters, shipping over 45,000 metric tons annually across <strong>Valencia and Navel oranges, mandarins (Murcott, Fremont), lemons, and grapefruit</strong>.</p>",
    socialLinks: {
      contactPerson: "Sherif Hosny", contactDesignation: "Export Director",
      establishedYear: "2005", memberSince: "2016", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, Russia, GCC, South Asia, East Africa", domesticMarkets: "Egypt",
      certifications: "GlobalG.A.P., BRC, ISO 22000, SEDEX, HACCP", languages: ["Arabic", "English", "Russian"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-fruits",
    logoKeyword: "citrus,oranges", coverKeyword: "orange,orchard", galleryKeywords: ["oranges,fresh", "mandarins", "lemon,citrus", "orange,grove", "citrus,packing", "oranges,box"],
  },
  {
    name: "Hoda Farouk",
    companyName: "Egyptian Strawberry Farms",
    email: "hoda@egyptian-strawberry.com", companyEmail: "sales@egyptian-strawberry.com",
    plan: "GOLD", country: "Egypt", city: "Qalyubia", countryCode: "EG", postalCode: "13621",
    businessType: "Farm / Producer", employeeCount: "201-500",
    phone: "+20-128-9988776", website: "https://www.egyptian-strawberry.com",
    address: "Quesna Agricultural Zone, Qalyubia Governorate",
    bio: "<p>Egyptian Strawberry Farms is a specialized producer and exporter of <strong>fresh and IQF strawberries</strong>. Egypt is among the world's top 5 strawberry producers.</p>",
    socialLinks: {
      contactPerson: "Hoda Farouk", contactDesignation: "Managing Director",
      establishedYear: "2007", memberSince: "2017", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, Russia, GCC, East Asia", domesticMarkets: "Egypt",
      certifications: "GlobalG.A.P., BRC, IFS, ISO 22000, HACCP", languages: ["Arabic", "English"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-fruits",
    logoKeyword: "strawberry,farm", coverKeyword: "strawberry,field", galleryKeywords: ["strawberry,fresh", "strawberries,box", "strawberry,harvest", "strawberry,field", "frozen,strawberry", "strawberry,green"],
  },
  {
    name: "Wael Nassar",
    companyName: "Egyptian Potato Exporters Co.",
    email: "wael@egyptian-potato.com", companyEmail: "export@egyptian-potato.com",
    plan: "SILVER", country: "Egypt", city: "Damanhour", countryCode: "EG", postalCode: "22511",
    businessType: "Trading Company", employeeCount: "51-200",
    phone: "+20-100-1122334", website: "https://www.egyptian-potato.com",
    address: "Damanhour Industrial Zone, Beheira Governorate",
    bio: "<p>Egyptian Potato Exporters Co. is a leading trader of Egyptian <strong>table and processing potatoes</strong>, based in Beheira. We ship over 30,000 metric tons annually.</p>",
    socialLinks: {
      contactPerson: "Wael Nassar", contactDesignation: "Export Manager",
      establishedYear: "2010", memberSince: "2018", membershipStatus: "SILVER Member",
      marketsCovered: "EU, Russia, GCC, West Africa", domesticMarkets: "Egypt, Libya",
      certifications: "GlobalG.A.P., ISO 22000, HACCP", languages: ["Arabic", "English"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-vegetables",
    logoKeyword: "potato,farm", coverKeyword: "potato,field", galleryKeywords: ["potatoes,fresh", "potato,harvest", "potato,bag", "potato,farm", "potato,washed", "spunta,potato"],
  },
  {
    name: "Tarek Samir",
    companyName: "Nile Onion Export",
    email: "tarek@nile-onion.com", companyEmail: "info@nile-onion.com",
    plan: "SILVER", country: "Egypt", city: "Minya", countryCode: "EG", postalCode: "61511",
    businessType: "Trading Company", employeeCount: "51-200",
    phone: "+20-128-5566778", website: "https://www.nile-onion.com",
    address: "Agricultural Road, Minya, Upper Egypt",
    bio: "<p>Nile Onion Export is a specialist exporter of Egyptian <strong>red, white, and golden onions</strong>, working with over 200 partner farms. Annual export exceeds 25,000 metric tons.</p>",
    socialLinks: {
      contactPerson: "Tarek Samir", contactDesignation: "Operations Director",
      establishedYear: "2008", memberSince: "2019", membershipStatus: "SILVER Member",
      marketsCovered: "Russia, GCC, West Africa", domesticMarkets: "Egypt",
      certifications: "GlobalG.A.P., HACCP, ISO 9001", languages: ["Arabic", "English"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-vegetables",
    logoKeyword: "onion,farm", coverKeyword: "onion,field", galleryKeywords: ["red,onion", "white,onion", "onions,bags", "onion,harvest", "onion,mesh", "onion,fresh"],
  },
  {
    name: "Aya Mostafa",
    companyName: "Delta Fresh Produce Co.",
    email: "aya@deltafresh-eg.com", companyEmail: "sales@deltafresh-eg.com",
    plan: "GOLD", country: "Egypt", city: "Damietta", countryCode: "EG", postalCode: "34511",
    businessType: "Manufacturer/ OEM", employeeCount: "201-500",
    phone: "+20-100-7788990", website: "https://www.deltafresh-eg.com",
    address: "Damietta Port Industrial Zone, Damietta Governorate",
    bio: "<p>Delta Fresh Produce Co. is a full-service Egyptian fresh produce exporter operating from Damietta. Our portfolio covers <strong>citrus, strawberries, potatoes, onions, green beans, and fresh herbs</strong>.</p>",
    socialLinks: {
      contactPerson: "Aya Mostafa", contactDesignation: "Export Director",
      establishedYear: "2012", memberSince: "2017", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, Russia, GCC, West Africa, UK", domesticMarkets: "Egypt",
      certifications: "GlobalG.A.P., BRC, IFS, ISO 22000, SEDEX", languages: ["Arabic", "English", "French"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-vegetables",
    logoKeyword: "fresh,produce", coverKeyword: "fresh,vegetables", galleryKeywords: ["fresh,vegetables", "tomatoes,fresh", "green,beans", "fresh,herbs", "vegetable,packing", "produce,market"],
  },
  {
    name: "Hamza Benjelloun",
    companyName: "Moroccan Citrus Export S.A.",
    email: "hamza@moroccan-citrus.ma", companyEmail: "export@moroccan-citrus.ma",
    plan: "GOLD", country: "Morocco", city: "Agadir", countryCode: "MA", postalCode: "80000",
    businessType: "Manufacturer/ OEM", employeeCount: "201-500",
    phone: "+212-661-112233", website: "https://www.moroccan-citrus.ma",
    address: "Zone Industrielle Tassila, Agadir, Souss-Massa",
    bio: "<p>Moroccan Citrus Export S.A. is one of Morocco's leading citrus exporters, based in Agadir. We ship over 40,000 metric tons of <strong>oranges, mandarins, clementines, lemons, and grapefruit</strong>.</p>",
    socialLinks: {
      contactPerson: "Hamza Benjelloun", contactDesignation: "General Manager",
      establishedYear: "2003", memberSince: "2016", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, Russia, North America, GCC, West Africa", domesticMarkets: "Morocco",
      certifications: "GlobalG.A.P., BRC, IFS, ISO 22000, SEDEX",
      languages: ["Arabic", "French", "English", "Spanish"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-fruits",
    logoKeyword: "moroccan,citrus", coverKeyword: "agadir,citrus", galleryKeywords: ["nadorcott,mandarin", "oranges,morocco", "citrus,grove", "lemons,fresh", "citrus,packing", "clementines"],
  },
  {
    name: "Salma El Idrissi",
    companyName: "Agadir Strawberry Co.",
    email: "salma@agadir-strawberry.ma", companyEmail: "sales@agadir-strawberry.ma",
    plan: "GOLD", country: "Morocco", city: "Agadir", countryCode: "MA", postalCode: "80000",
    businessType: "Manufacturer/ OEM", employeeCount: "201-500",
    phone: "+212-662-998877", website: "https://www.agadir-strawberry.ma",
    address: "Route de Taroudant km 22, Agadir, Souss-Massa",
    bio: "<p>Agadir Strawberry Co. is a dedicated <strong>fresh and frozen strawberry producer</strong> based in the Souss-Massa region. We cultivate 480 hectares and ship 14,000 metric tons/year.</p>",
    socialLinks: {
      contactPerson: "Salma El Idrissi", contactDesignation: "Export Manager",
      establishedYear: "2009", memberSince: "2017", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, Russia, UK", domesticMarkets: "Morocco",
      certifications: "GlobalG.A.P., BRC, IFS, ISO 22000",
      languages: ["Arabic", "French", "English", "Spanish"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-fruits",
    logoKeyword: "morocco,strawberry", coverKeyword: "strawberry,garden", galleryKeywords: ["moroccan,strawberry", "fresh,strawberry", "strawberry,packing", "strawberry,harvest", "frozen,strawberry", "strawberry,green"],
  },
  {
    name: "Rachid Berrada",
    companyName: "Moroccan Potato Union",
    email: "rachid@moroccan-potato.ma", companyEmail: "export@moroccan-potato.ma",
    plan: "SILVER", country: "Morocco", city: "Meknès", countryCode: "MA", postalCode: "50000",
    businessType: "Cooperative", employeeCount: "51-200",
    phone: "+212-661-445566", website: "https://www.moroccan-potato.ma",
    address: "Route d'El Hajeb km 15, Meknès",
    bio: "<p>Moroccan Potato Union is a cooperative of 180 potato growers based in the Meknès-El Hajeb plateau. Combined production is 45,000 metric tons annually.</p>",
    socialLinks: {
      contactPerson: "Rachid Berrada", contactDesignation: "Cooperative President",
      establishedYear: "2013", memberSince: "2020", membershipStatus: "SILVER Member",
      marketsCovered: "EU, West Africa", domesticMarkets: "Morocco",
      certifications: "GlobalG.A.P. (partial), ONSSA, HACCP", languages: ["Arabic", "French"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-vegetables",
    logoKeyword: "morocco,potato", coverKeyword: "potato,field,morocco", galleryKeywords: ["moroccan,potato", "potato,fresh", "potato,farm", "potato,bag", "potato,harvest", "potato,washed"],
  },
  {
    name: "Nadia Tazi",
    companyName: "Souss Valley Vegetables Co.",
    email: "nadia@soussvalley-veg.ma", companyEmail: "info@soussvalley-veg.ma",
    plan: "GOLD", country: "Morocco", city: "Taroudant", countryCode: "MA", postalCode: "83000",
    businessType: "Manufacturer/ OEM", employeeCount: "201-500",
    phone: "+212-662-223344", website: "https://www.soussvalley-veg.ma",
    address: "Route de Marrakech, Taroudant, Souss-Massa",
    bio: "<p>Souss Valley Vegetables Co. is a major producer and exporter of <strong>fresh vegetables from the Souss plain</strong> — tomatoes, green beans, zucchini, peppers, cucumbers, and eggplants.</p>",
    socialLinks: {
      contactPerson: "Nadia Tazi", contactDesignation: "Commercial Director",
      establishedYear: "2011", memberSince: "2018", membershipStatus: "GOLD PLUS Member",
      marketsCovered: "EU, UK, West Africa", domesticMarkets: "Morocco",
      certifications: "GlobalG.A.P., BRC, IFS, ISO 22000",
      languages: ["Arabic", "French", "English", "Spanish"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-vegetables",
    logoKeyword: "morocco,vegetables", coverKeyword: "vegetable,farm", galleryKeywords: ["tomatoes,fresh", "green,beans,fresh", "zucchini,fresh", "bell,peppers", "cucumber,fresh", "eggplant,fresh"],
  },
  {
    name: "Omar El Fassi",
    companyName: "Marrakech Fresh Fruits",
    email: "omar@marrakech-fresh.ma", companyEmail: "sales@marrakech-fresh.ma",
    plan: "SILVER", country: "Morocco", city: "Marrakech", countryCode: "MA", postalCode: "40000",
    businessType: "Trading Company", employeeCount: "51-200",
    phone: "+212-661-778899", website: "https://www.marrakech-fresh.ma",
    address: "Zone Sidi Ghanem, Marrakech",
    bio: "<p>Marrakech Fresh Fruits is a Moroccan fresh fruit trader specialized in <strong>stone fruits, melons, watermelons, and grapes</strong> from the Haouz plain.</p>",
    socialLinks: {
      contactPerson: "Omar El Fassi", contactDesignation: "Export Manager",
      establishedYear: "2010", memberSince: "2019", membershipStatus: "SILVER Member",
      marketsCovered: "EU, Russia, UK", domesticMarkets: "Morocco",
      certifications: "GlobalG.A.P., HACCP, ONSSA", languages: ["Arabic", "French", "English"],
    },
    primaryCategory: "fruits-vegetables", primarySubCategory: "fresh-fruits",
    logoKeyword: "marrakech,fruits", coverKeyword: "marrakech,orchard", galleryKeywords: ["peaches,fresh", "nectarines", "watermelon,fresh", "cantaloupe", "grapes,fresh", "plums,fresh"],
  },
];

module.exports = { companies };